export * from "./landingPage/DoctorCardSkeleton"
export * from "./landingPage/ServiceCardSkeleton"
export * from "./landingPage/TeamMemberSkeleton"
export * from "./landingPage/TestimonialSkeleton"
export * from "./ProfilePage/ProfileSkeleton"