"""empty message

Revision ID: 0ca00fac7845
Revises: f66ff48927b7
Create Date: 2026-02-17 18:31:26.426727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0ca00fac7845'
down_revision: Union[str, None] = 'f66ff48927b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_slot',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('doctor_id', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Timestamp when record was created'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was last updated'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when record was soft-deleted. NULL means active.'),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctor.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_slot_deleted_at'), 'blocked_slot', ['deleted_at'], unique=False)
    op.alter_column('admin', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('admin', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.drop_column('admin', 'deleted_at')
    op.alter_column('appointment', 'appointment_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('appointment', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('appointment', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('appointment', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_appointment_deleted_at'), 'appointment', ['deleted_at'], unique=False)
    op.alter_column('clinic', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('clinic', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('clinic', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_clinic_deleted_at'), 'clinic', ['deleted_at'], unique=False)
    op.alter_column('diagnosis', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('diagnosis', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('diagnosis', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_diagnosis_deleted_at'), 'diagnosis', ['deleted_at'], unique=False)
    op.add_column('doctor', sa.Column('specializations', sa.JSON(), nullable=True))
    op.add_column('doctor', sa.Column('services', sa.JSON(), nullable=True))
    op.add_column('doctor', sa.Column('education', sa.JSON(), nullable=True))
    op.add_column('doctor', sa.Column('experience', sa.JSON(), nullable=True))
    op.alter_column('doctor', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('doctor', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('doctor', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_doctor_deleted_at'), 'doctor', ['deleted_at'], unique=False)
    op.create_unique_constraint(None, 'doctor', ['license_no'])
    op.drop_constraint(op.f('doctor_user_id_fkey'), 'doctor', type_='foreignkey')
    op.create_foreign_key(None, 'doctor', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('doctor', 'specialization')
    op.alter_column('doctor_schedule', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('doctor_schedule', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('doctor_schedule', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('doctor_schedule', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('doctor_schedule', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_doctor_schedule_deleted_at'), 'doctor_schedule', ['deleted_at'], unique=False)
    op.alter_column('medicine', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('medicine', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('medicine', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_medicine_deleted_at'), 'medicine', ['deleted_at'], unique=False)
    op.alter_column('patient', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('patient', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('patient', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_patient_deleted_at'), 'patient', ['deleted_at'], unique=False)
    op.drop_constraint(op.f('patient_user_id_fkey'), 'patient', type_='foreignkey')
    op.create_foreign_key(None, 'patient', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('prescription', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('prescription', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('prescription', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_prescription_deleted_at'), 'prescription', ['deleted_at'], unique=False)
    op.alter_column('prescription_medicine', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('prescription_medicine', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('prescription_medicine', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_prescription_medicine_deleted_at'), 'prescription_medicine', ['deleted_at'], unique=False)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('refresh_tokens', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.drop_column('refresh_tokens', 'deleted_at')
    op.alter_column('test', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('test', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('test', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_test_deleted_at'), 'test', ['deleted_at'], unique=False)
    op.add_column('timeslot', sa.Column('slot_type', sa.String(), nullable=False))
    op.alter_column('timeslot', 'start_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('timeslot', 'end_time',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('timeslot', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('timeslot', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('timeslot', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_timeslot_deleted_at'), 'timeslot', ['deleted_at'], unique=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('users', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.alter_column('users', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_timeslot_deleted_at'), table_name='timeslot')
    op.alter_column('timeslot', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('timeslot', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('timeslot', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('timeslot', 'end_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('timeslot', 'start_time',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('timeslot', 'slot_type')
    op.drop_index(op.f('ix_test_deleted_at'), table_name='test')
    op.alter_column('test', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('test', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('test', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.add_column('refresh_tokens', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('refresh_tokens', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('refresh_tokens', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_prescription_medicine_deleted_at'), table_name='prescription_medicine')
    op.alter_column('prescription_medicine', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('prescription_medicine', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('prescription_medicine', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_prescription_deleted_at'), table_name='prescription')
    op.alter_column('prescription', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('prescription', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('prescription', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_constraint(None, 'patient', type_='foreignkey')
    op.create_foreign_key(op.f('patient_user_id_fkey'), 'patient', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_patient_deleted_at'), table_name='patient')
    op.alter_column('patient', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('patient', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('patient', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_medicine_deleted_at'), table_name='medicine')
    op.alter_column('medicine', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('medicine', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('medicine', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_doctor_schedule_deleted_at'), table_name='doctor_schedule')
    op.alter_column('doctor_schedule', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('doctor_schedule', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('doctor_schedule', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('doctor_schedule', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('doctor_schedule', 'start_time',
               existing_type=sa.Time(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.add_column('doctor', sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'doctor', type_='foreignkey')
    op.create_foreign_key(op.f('doctor_user_id_fkey'), 'doctor', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'doctor', type_='unique')
    op.drop_index(op.f('ix_doctor_deleted_at'), table_name='doctor')
    op.alter_column('doctor', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('doctor', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('doctor', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_column('doctor', 'experience')
    op.drop_column('doctor', 'education')
    op.drop_column('doctor', 'services')
    op.drop_column('doctor', 'specializations')
    op.drop_index(op.f('ix_diagnosis_deleted_at'), table_name='diagnosis')
    op.alter_column('diagnosis', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('diagnosis', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('diagnosis', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_clinic_deleted_at'), table_name='clinic')
    op.alter_column('clinic', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('clinic', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('clinic', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_appointment_deleted_at'), table_name='appointment')
    op.alter_column('appointment', 'deleted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was soft-deleted. NULL means active.',
               existing_nullable=True)
    op.alter_column('appointment', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('appointment', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.alter_column('appointment', 'appointment_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('admin', sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.alter_column('admin', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was last updated',
               existing_nullable=True)
    op.alter_column('admin', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               comment=None,
               existing_comment='Timestamp when record was created',
               existing_nullable=False)
    op.drop_index(op.f('ix_blocked_slot_deleted_at'), table_name='blocked_slot')
    op.drop_table('blocked_slot')
    # ### end Alembic commands ###

