export * from "./appointment.urls";
export * from "./auth.urls";
export * from "./clinic.urls";
export * from "./contact.urls";
export * from "./doctor.urls";
export * from "./feedback.urls";
export * from "./patient.urls";
export * from "./public.urls";
export * from "./reminders.urls";